### ISSUE TITLE
New release for log4js removal

### ISSUE THREAD

**Issue by YannickMeeus** [Workable/rabbit-queue#30]
Hi there! we were wondering when you'd be pushing a new release to NPM.

We're particularly interested in the changes that remove the Log4js dependency, as it's been a bit of a pain to get working in our particular environment.

Thanks a bunch for the library though, I do appreciate it 🙏

**Comment by nikostoulas** [comment]
Hi @YannickMeeus!
Since the work is already in master we will test it a bit more and make a release soon. Before the end of this week. I hope this also works for you.
It will  be a major version change and will include the usage of different connections for publishing and consuming messages. 
Thanks for the good words!

**Comment by nikostoulas** [comment]
Version 5.0.0-beta.1 was just published if you want to check it out @YannickMeeus.

**Comment by YannickMeeus** [comment]
Good stuff, I'll let people know so we can poke that for a while. Thanks for getting back to me 🙏

**Comment by nikostoulas** [comment]
@YannickMeeus v5.0.0 is now published. I am now closing this issue. 
Please open a new one if you face any issues!
